### ISSUE TITLE
Maybe the project is still in progress？

### ISSUE THREAD

**Issue by melodyWxy** [Bogdan-Lyashenko/vs-code-codecrumbs#1]
At least that's what I expect. Does anyone respond to me?

**Comment by Bogdan-Lyashenko** [comment]
@melodyWxy hi, actually it was completed, though not in this repo :) So there is Codecrumbs 2.0 Desktop app and VS code extension that integrates with it. Checkout details here https://codecrumbs.io/

**Comment by melodyWxy** [comment]
@Bogdan-Lyashenko 
Hello, technology God.
In fact, I have experienced V2 desktop application. There is no doubt that it is a great design, but unfortunately its code does not seem to be open source.This is my issue -- I want to learn it more ...
